export default {
  LOGO: require('./logo.png'),
  GOOGLELOGO: require('./google.png'),
  EYESOFF: require('./eyeoff.png'),
  FACEBOOKLOGO: require('./facebook.png'),
  EYEON: require('./eyeon.png'),
  HOMEICON: require('./Home.png'),
  BAGICON: require('./Bag.png'),
  PROFILEICON: require('./Profile.png'),
  SETTINGSICON: require('./Setting.png'),
  LIKEICON: require('./Heart.png'),
  SEARCHICON: require('./searchIcon.png'),
  SMALLHEARTICON: require('./SmallHeartIcon.png'),
  STARICON: require('./Star.png'),
  SOFAIMG: require('./SofaImg.png'),
  ADDICON: require('./AddIcon.png'),
  CHAIR: require('./Chair.png'),
  CHAIRTWO: require('./ChairTwo.png'),
  SOFATWO: require('./SofaTwo.png'),
  SOFATHREE: require('./SofaThree.png'),
};
